-- 연습문제 
--1. 급여가 3000에서 5000사이인 직원의 이름과 소속 부서명을 출력
SELECT E.ENAME, D.DNAME
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO 
   AND SAL BETWEEN 3000 AND 50000;
   
SELECT E.ENAME, D.DNAME
  FROM EMP E INNER JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO 
 WHERE SAL BETWEEN 3000 AND 50000;
 
--2. 직급이 MANAGER  인 사원의 이름 부서명을 출력
SELECT E.ENAME, D.DNAME
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND E.JOB = UPPER ('MANAGER');
   
SELECT E.ENAME, D.DNAME
  FROM EMP E INNER JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
   AND E.JOB = UPPER ('MANAGER');
 
--3. ACCOUNTING 부서 소속 사원의 이름과 입사일 출력
SELECT E.ENAME, E.HIREDATE
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND D.DNAME = UPPER ('ACCOUNTING');   
   
SELECT E.ENAME, E.HIREDATE
  FROM EMP E INNER JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
WHERE UPPER(D.DNAME) = 'ACCOUNTING';
  

--4. 커미션을 받는 사원의 이름과 그가 속한 부셔명을 출력
SELECT E.ENAME, D.DNAME
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND E.COMM IS NOT NULL 
   AND E.COMM != 0;
   
SELECT E.ENAME, D.DNAME
  FROM EMP E INNER JOIN DEPT D
 USING (DEPTNO)
 WHERE E.COMM IS NOT NULL
   AND E.COMM != 0;

--5. 뉴욕에서 근무하는 사원의 이름과 급여를 출력
SELECT E.ENAME, E.SAL
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND D.LOC = UPPER('NEW YORK');
 
SELECT E.ENAME, E.SAL
  FROM EMP E INNER JOIN DEPT D
 USING (DEPTNO)
 WHERE D.LOC = 'NEW YORK';
   
--6. 급여가 1200 이하인 사원 이름과 급여, 근무지 출력
SELECT E.ENAME, E.SAL, D.LOC
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND SAL <= 1200;
   
SELECT E.ENAME, E.SAL, D.LOC
  FROM EMP E INNER JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
 WHERE E.SAL <= 1200;
 
--7. SMITH와 동일한 근무지에서 근무하는 사원의 이름을 출력 @@
SELECT COWORKER.ENAME, COWORKER.DEPTNO
  FROM EMP WORKER INNER JOIN EMP COWORKER
    ON WORKER.DEPTNO = COWORKER.DEPTNO
 WHERE WORKER.ENAME = UPPER('SMITH')
   AND COWORKER.ENAME <> UPPER('SMITH');

--8. 매니저가 KING인 사원듫의 이름과 직급을 출력
SELECT WORKER.ENAME, WORKER.JOB
  FROM EMP WORKER, EMP MANAGER
 WHERE MANAGER.EMPNO = WORKER.MGR
   AND MANAGER.ENAME = UPPER('KING');
   
SELECT WORKER.ENAME, WORKER.JOB
  FROM EMP WORKER INNER JOIN EMP MANAGER
    ON MANAGER.EMPNO = WORKER.MGR
 WHERE MANAGER.ENAME = UPPER('KING');
 
--9. 급여가 2000 초과인 사원들의 부서 번호 부서 이름 사원 번호 월급을 출력
SELECT D.DEPTNO, D.DNAME, E.ENAME, E.EMPNO, E.SAL
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND E.SAL > 2000;

--SELECT D.DEPTNO, D.DNAME, E.ENAME, E.EMPNO, E.SAL
SELECT DEPTNO, D.DNAME, E.ENAME, E.EMPNO, E.SAL
  FROM EMP E INNER JOIN DEPT D
--    ON E.DEPTNO = D.DEPTNO
 USING (DEPTNO)   
 WHERE E.SAL > 2000; 
 
 SELECT D.DEPTNO, D.DNAME, E.ENAME, E.EMPNO, E.SAL
  FROM EMP E INNER JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
 WHERE E.SAL > 2000; 
   
--10. 각 부서별 평균 급여 최대 급여 사원수를 출력
SELECT AVG(SAL), MAX(SAL), COUNT(*), D.DNAME
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
 GROUP BY D.DNAME;
 
SELECT ROUND(AVG(SAL), 2), MAX(SAL), COUNT(*), D.DNAME
  FROM EMP E INNER JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
 GROUP BY D.DNAME;
 
SELECT ROUND(AVG(SAL), 2), MAX(SAL), COUNT(*), D.DNAME
  FROM EMP E INNER JOIN DEPT D
 USING (DEPTNO)
 GROUP BY D.DNAME;
 
--11. 모든 부서 정보와 사원 정보를 부서 번호 사원 이름 순으로 출력
SELECT D.DNAME, E.ENAME
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
 ORDER BY D.DEPTNO, E.ENAME;
 
SELECT D.DNAME, E.ENAME
  FROM EMP E INNER JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
 ORDER BY D.DEPTNO, E.ENAME;
 
SELECT D.*, E.*
  FROM EMP E INNER JOIN DEPT D
    ON E.DEPTNO (+) = D.DEPTNO
 ORDER BY D.DEPTNO, E.ENAME;
 
--12. 부서 번호 부서 이름 사원번호 사원이름 LOSAL HISAL GRADE 매니저 번호 매니저 이름을 출력
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, S.LOSAL, S.HISAL, S.GRADE, M.EMPNO, M.ENAME
 FROM EMP E INNER JOIN DEPT D
   ON E.DEPTNO = D.DEPTNO
FULL OUTER JOIN EMP M
ON E.MGR = M.EMPNO
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

 
